const DEF=[{id:'cat_comida',emoji:'🍔',name:'Comida',type:'expense',budget:15000,archived:false},{id:'cat_transporte',emoji:'🚇',name:'Transporte',type:'expense',budget:3000,archived:false},{id:'cat_entretenimiento',emoji:'🎬',name:'Entretenimiento',type:'expense',budget:5000,archived:false},{id:'cat_servicios',emoji:'🏠',name:'Servicios',type:'expense',budget:6000,archived:false},{id:'cat_ropa',emoji:'👗',name:'Ropa',type:'expense',budget:5000,archived:false},{id:'cat_salud',emoji:'💊',name:'Salud',type:'expense',budget:3000,archived:false},{id:'cat_salario',emoji:'💰',name:'Salario',type:'income',budget:0,archived:false},{id:'cat_otros',emoji:'📦',name:'Otros',type:'both',budget:0,archived:false}];

const OLDMAP={'🍔 Comida':'cat_comida','🚇 Transporte':'cat_transporte','🎬 Entretenimiento':'cat_entretenimiento','🏠 Servicios':'cat_servicios','👗 Ropa':'cat_ropa','💊 Salud':'cat_salud','💰 Salario':'cat_salario','📦 Otros':'cat_otros'};

function cat(id){return meta.categories.find(c=>c.id===id)||meta.categories.find(c=>c.id==='cat_otros')||meta.categories[0]}

function label(c){return c?c.emoji+' '+c.name:'📦 Otros'}

function normCat(c){return{id:c.id||mkCatId(c.name||'categoria'),emoji:c.emoji||'📦',name:c.name||'Categoría',type:c.type||'expense',budget:Math.max(0,Number(c.budget)||0),archived:!!c.archived}}

function allowed(c,t,arch=false){return c&&(arch||!c.archived)&&(c.type==='both'||c.type===t)}

function fillCats(id,t,sel=''){let s=document.getElementById(id),arr=meta.categories.filter(c=>allowed(c,t));let keep=sel&&meta.categories.find(c=>c.id===sel);if(keep&&!arr.find(c=>c.id===keep.id))arr=[keep,...arr];s.innerHTML=arr.map(c=>'<option value="'+escapeHTML(c.id)+'">'+escapeHTML(label(c)+(c.archived?' (archivada)':''))+'</option>').join('');s.value=arr.find(c=>c.id===sel)?.id||arr[0]?.id||''}

function setType(t){txType=t;document.getElementById('pill-expense').classList.toggle('active',t==='expense');document.getElementById('pill-income').classList.toggle('active',t==='income');fillCats('f-cat',t)}

function setEditType(t){editType=t;document.getElementById('e-pill-expense').classList.toggle('active',t==='expense');document.getElementById('e-pill-income').classList.toggle('active',t==='income');fillCats('e-cat',t,document.getElementById('e-cat').value)}

function mkCatId(n){return 'cat_'+String(n).toLowerCase().normalize('NFD').replace(new RegExp('[\\u0300-\\u036f]','g'),'').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')+'_'+Date.now().toString(36)}

async function createCategory(){let emoji=document.getElementById('new-cat-emoji').value.trim()||'📦',name=document.getElementById('new-cat-name').value.trim(),type=document.getElementById('new-cat-type').value,budget=Number(document.getElementById('new-cat-budget').value)||0;if(!name)return toast('Ingresa un nombre');let c={id:mkCatId(name),emoji,name,type,budget:Math.max(0,budget),archived:false};meta.categories.push(c);let r=await writeMeta();if(!r.ok){meta.categories=meta.categories.filter(x=>x.id!==c.id);return}document.getElementById('new-cat-emoji').value='';document.getElementById('new-cat-name').value='';document.getElementById('new-cat-budget').value='';renderAll();if(!r.degraded)toast('Categoría creada')}

async function saveCategory(id){let c=cat(id),old={...c},name=document.getElementById('cat-name-'+id).value.trim();if(!name)return toast('Nombre requerido');c.emoji=document.getElementById('cat-emoji-'+id).value.trim()||'📦';c.name=name;c.type=document.getElementById('cat-type-'+id).value;c.budget=Math.max(0,Number(document.getElementById('cat-budget-'+id).value)||0);let r=await writeMeta();if(!r.ok){Object.assign(c,old);return}renderAll();if(!r.degraded)toast('Categoría guardada')}

async function archiveOrDeleteCategory(id){let old=JSON.parse(JSON.stringify(meta.categories)),i=meta.categories.findIndex(c=>c.id===id);if(i<0)return;let has=transactions.some(t=>t.catId===id);if(has)meta.categories[i].archived=true;else meta.categories.splice(i,1);let r=await writeMeta();if(!r.ok){meta.categories=old;return}renderAll();if(!r.degraded)toast(has?'Categoría archivada':'Categoría eliminada')}

async function restoreCategory(id){let c=cat(id),old=c.archived;c.archived=false;let r=await writeMeta();if(!r.ok){c.archived=old;return}renderAll();if(!r.degraded)toast('Categoría restaurada')}

function renderCategories(){document.getElementById('cat-list').innerHTML=meta.categories.map(c=>'<div class="cat-card '+(c.archived?'archived':'')+'"><div class="cat-head"><div><div class="cat-title">'+escapeHTML(label(c))+'</div><div class="cat-sub">'+escapeHTML(c.type)+(c.archived?' · archivada':'')+'</div></div></div><div class="form-row"><div class="field"><label>Emoji</label><input id="cat-emoji-'+escapeHTML(c.id)+'" value="'+escapeHTML(c.emoji)+'"></div><div class="field" style="flex:2"><label>Nombre</label><input id="cat-name-'+escapeHTML(c.id)+'" value="'+escapeHTML(c.name)+'"></div></div><div class="form-row"><div class="field"><label>Tipo</label><select id="cat-type-'+escapeHTML(c.id)+'"><option value="expense" '+(c.type==='expense'?'selected':'')+'>expense</option><option value="income" '+(c.type==='income'?'selected':'')+'>income</option><option value="both" '+(c.type==='both'?'selected':'')+'>both</option></select></div><div class="field"><label>Budget</label><input id="cat-budget-'+escapeHTML(c.id)+'" type="number" value="'+escapeHTML(c.budget||'')+'"></div></div><div class="actions-row"><button class="btn cat-save" data-id="'+escapeHTML(c.id)+'">Guardar</button>'+(c.archived?'<button class="btn ghost cat-restore" data-id="'+escapeHTML(c.id)+'">Restaurar</button>':'<button class="btn danger cat-archive" data-id="'+escapeHTML(c.id)+'">Archivar/eliminar</button>')+'</div></div>').join('');document.querySelectorAll('.cat-save').forEach(b=>b.onclick=()=>saveCategory(b.dataset.id));document.querySelectorAll('.cat-restore').forEach(b=>b.onclick=()=>restoreCategory(b.dataset.id));document.querySelectorAll('.cat-archive').forEach(b=>b.onclick=()=>archiveOrDeleteCategory(b.dataset.id))}
