function monthKey(t){return t.date?t.date.slice(0,7).replace('-','_'):''}

function ars(t){return Number(t.amountARS??t.amount??0)||0}

function migrateTx(o){let cur=CURRENCIES.includes(o.currency)?o.currency:'ARS',ao=Number(o.amountOriginal??o.amount??0),rt=cur==='ARS'?1:Number(o.rateToARS)||0;return{id:Number(o.id)||Date.now(),type:o.type==='income'?'income':'expense',desc:String(o.desc||'Sin descripción'),catId:o.catId||OLDMAP[o.cat||o.catName]||'cat_otros',date:validDate(o.date)?o.date:getLocalDateString(),amountOriginal:ao,currency:cur,rateToARS:rt,amountARS:Number(o.amountARS??(ao*rt))||0,rateProvider:o.rateProvider||(cur==='ARS'?'ARS':'manual'),rateFetchedAt:o.rateFetchedAt||null}}
async function writeMeta(touch=true){if(touch)touchMeta();let r=await storageSet(META_KEY,JSON.stringify(meta));return r}

function formTx(p,type,old={}){let desc=document.getElementById(p+'-desc').value.trim(),raw=document.getElementById(p+'-amount').value,cur=document.getElementById(p+'-currency').value,catId=document.getElementById(p+'-cat').value,date=document.getElementById(p+'-date').value||getLocalDateString(),rate=cur==='ARS'?1:Number(document.getElementById(p+'-rate').value);if(!desc)return toast('descReq'),null;if(!validAmount(raw))return toast('amountReq'),null;if(!validDate(date))return toast('badDate'),null;if(cur!=='ARS'&&(!Number.isFinite(rate)||rate<=0))return toast('rateReq'),null;if(!cat(catId))return toast('catReq'),null;let amountOriginal=Number(raw),k=cache(cur);return{...old,id:old.id||meta.nextId++,type,desc,catId,date,amountOriginal,currency:cur,rateToARS:rate,amountARS:amountOriginal*rate,rateProvider:cur==='ARS'?'ARS':k.provider,rateFetchedAt:cur==='ARS'?null:k.at}}

async function addTx(){let t=formTx('f',txType);if(!t)return;transactions.unshift(t);let r=await saveMonth(monthKey(t));if(!r.ok){transactions=transactions.filter(x=>x.id!==t.id);meta.nextId=Math.max(1,meta.nextId-1);return}document.getElementById('f-desc').value='';document.getElementById('f-amount').value='';preview('f');renderAll();if(!r.degraded)toast(txType==='expense'?'− Gasto agregado':'+ Ingreso agregado');switchPage('home')}

async function delTx(id){if(!confirm(t('confirmDelete')))return;let old=[...transactions];transactions=transactions.filter(t=>String(t.id)!==String(id));let r=await saveAll();if(!r.ok){transactions=old;renderAll();return}renderAll()}

function openEdit(id){let t=transactions.find(x=>String(x.id)===String(id));if(!t)return;editId=id;editType=t.type;document.getElementById('e-desc').value=t.desc;document.getElementById('e-amount').value=t.amountOriginal;document.getElementById('e-currency').value=t.currency;document.getElementById('e-rate').value=t.rateToARS;document.getElementById('e-date').value=t.date;fillCats('e-cat',t.type,t.catId);setEditType(t.type);uiCurrency('e');document.getElementById('edit-modal').classList.add('open')}

function closeEditModal(e){if(e&&e.target!==document.getElementById('edit-modal'))return;document.getElementById('edit-modal').classList.remove('open')}

async function saveEdit(){let i=transactions.findIndex(t=>String(t.id)===String(editId));if(i<0)return;let oldTx={...transactions[i]},oldK=monthKey(transactions[i]),t=formTx('e',editType,{id:transactions[i].id});if(!t)return;transactions[i]=t;let r=oldK!==monthKey(t)?await saveAll():await saveMonth(monthKey(t));if(!r.ok){transactions[i]=oldTx;return}closeEditModal();renderAll();if(!r.degraded)toast('Operación actualizada')}

function txHTML(t,a){let c=cat(t.catId),sign=t.type==='income'?'+':'−',orig=sign+money(t.amountOriginal,t.currency),ap=t.currency==='ARS'?'':' ≈ '+fmt(t.amountARS),id=escapeHTML(String(t.id));return '<div class="tx-item"><div class="tx-icon '+escapeHTML(t.type)+'">'+escapeHTML(c?.emoji||'📦')+'</div><div class="tx-info"><div class="tx-desc">'+escapeHTML(t.desc)+'</div><div class="tx-meta">'+escapeHTML(label(c))+' · '+escapeHTML(t.date)+(c?.archived?' · archivada':'')+'</div></div><div class="tx-amount '+escapeHTML(t.type)+'">'+escapeHTML(orig+ap)+'</div>'+(a?'<div><button class="tx-btn" onclick="openEdit(\''+id+'\')">✎</button><button class="tx-btn" onclick="delTx(\''+id+'\')">✕</button></div>':'')+'</div>'}